# training params
LR: 0.0001
EPOCHS: 128
MAX_PATIENCE: 64

# dataset/dataloader params
DS_PATH: /goat-nas/Datasets/spal/spal_cuts
BATCH_SIZE: 32
CAM_ID: cam_1
N_WORKERS: 4
DATA_AUG: False

# loss params
LOSS_FN: L1+MS_SSIM
SCORE_FN: CODE_MSE_LOSS

# autoencoder bottleneck/code params
CODE_CHANNELS: 3
CODE_H: 4
CODE_W: 4
CODE_NOISE: 0

DEVICE: cuda
